### ISSUE TITLE
Could not pass event PlayerJoinEvent to BSwear v4.2.2

### ISSUE THREAD

**Issue by braddevans** [BSwear/BSwear#9]
[02:35:19 ERROR]: Could not pass event PlayerJoinEvent to BSwear v4.2.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at io.github.bswearteam.bswear.SwearUtils.hasSweared(SwearUtils.java:108) ~[?:?]
        at io.github.bswearteam.bswear.SwearUtils.getPlrSwears(SwearUtils.java:96) ~[?:?]
        at io.github.bswearteam.bswear.OnJoin.onPlayerJoin(OnJoin.java:15) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
        ... 14 more

**Comment by braddevans** [comment]
https://mods.curse.com/bukkit-plugins/minecraft/bswear
it does say it support 1.12

**Comment by pisaiah** [comment]
Should be fixed in latest commit. will upload release to BukkitDev & SpigotMC soon.

**Comment by pisaiah** [comment]
Fixed in release version 4.2.3 waiting for Bukkit to aprove file.
